---
- name: enable pam_limits.so
  copy:
    src=files/common-session
    dest=/etc/pam.d/common-session

- name: set file descriptor limits
  copy:
    src=files/limits.conf
    dest=/etc/security/limits.conf
